## PE.py
## Program by Valerie Lambert - 8/8/13

"""
Project Euler Problem 2- - - -
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

    1,2,3,5,8,13,21,34,55,89,...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
- - - - - - - - - - - - - - - -

Since each third term in the Fibonacci sequence is even, a simple
solution is to calculate every 3 terms and add to the total.
"""

def evenFibSum(max_num):
    fib_sum = 0
    a = 1
    b = 1
    c = a+b
    while c<=max_num:
        fib_sum += c
        a = b+c
        b = c+a
        c = a+b
    return fib_sum

def main():
    print(evenFibSum(4000000))

main()

