// PE.java
// Program by Valerie Lambert

/*  Project Euler Problem 2- - - -
 *  Each new term in the Fibonacci sequence is generated by adding the
 *  previous two terms. By starting with 1 and 2, the first terms will be:
 *
 *      1,2,3,5,8,13,21,24,55,89,...
 *
 *  By considering the terms in the Fibonacci sequence whose values do not
 *  exceed four million, find the sum of the even-valued terms.
 *  - - - - - - - - - - - - - - - -
 *
 *  Java solution for Problem 2.
 */

public class PE2 {

    private long max_fib;

    public PE2(long num) {
        max_fib = num;
    }

    public long evenFibSum() {
        long sum = 0;
        long a = 1;
        long b = 1;
        long c = a+b;
        while (c <= max_fib) {
            sum += c;
            a = b+c;
            b = c+a;
            c = a+b;
        }
        return sum;
    }

    public static void main(String[] args) {
        PE2 p = new PE2(4000000);
        System.out.println(p.evenFibSum());
    }
}
